services:
  lnproxy-ts:
    container_name: lnproxy-ts
    build: .
    volumes:
      - /path/to/lnd/dir:/root/.lnd:ro
    environment:
      - CERT_PATH=/root/.lnd/tls.cert
      - MACAROON_PATH=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      - SOCKET=polar-n1-alice:10009
networks:
  default:
    name: 1_default
    external: true
